### ISSUE TITLE
API: RPC resources located under /restconf/data rather than /restconf/operation

### ISSUE THREAD

**Issue by cgmcintyr** [freeconf/yang#17]
Please correct me if I'm wrong, but the RESTCONF specification seems to require RPC sections of the yang model be accessible under `POST {+restconf}/operations/<operation>` (see [section-3.6](https://tools.ietf.org/html/rfc8040#section-3.6)). 

However in the car example (https://github.com/freeconf/examples/tree/master/car) RPC's are accessed under `restconf/data`. An example of this being starting the car, which is done using `curl -XPOST http://localhost:8080/restconf/data/car:start`.

Is there a reason FreeCONF does this? If so is there anywhere I can query what operations are supported and what arguments each argument take?

**Comment by dhubler** [comment]
re: RPCs under operations
I was not aware of that requirement.  Thanks for pointing that out, we
should consider this a bug.

re: query what operations
you mean at runtime or documentation describing what the URLs are?

**Comment by dhubler** [comment]
Question/Follow-up.  I'm curious on what your interpreting the spec would
be:

If I have

module x {
     action y {...}
     rpc z {}

then it would be:

  POST restconf/data/x:y

and

  POST restconf/operations/x:z

that seem right?  If so, then yes, there's a bug where rpc are lumped in
w/actions.

**Comment by cgmcintyr** [comment]
Thanks for the quick reply. That was my reading of the specification, yes.

However I have only been reading through the spec today. I can look further into this and post back on this issue. I'm interested in using gconf to learn more about RestCONF and YANG, so would be happy to work on a pull request if it does turn out to be a bug :)

**Comment by cgmcintyr** [comment]
According to [RFC 7950 Section 7-.15](https://tools.ietf.org/html/rfc7950#section-7.15):

> The difference between an action and an rpc is that an action is tied
> to a node in the datastore, whereas an rpc is not.  When an action is
> invoked, the node in the datastore is specified along with the name
> of the action and the input parameters.

So an action could be thought of as a method on an object, which explains why it is attached to a URI with the format `{+restconf}/data/<data-resource-identifier>/<action>`.


Looking at the ABNF grammar defined in [RFC 7950 Section 14](https://tools.ietf.org/html/rfc7950#section-14): `rpc` statements have to be in the "module" level, whereas an `action` has to be within a `list`, `container` or `grouping` node (they can also be used in `uses-augment` or `augment` it seems, though I think this may be for overriding the `action` statement?).

From my understanding, say you have server farm that models a list of running servers:

```
module server-farm {

  container servers {
    list servers {
      key name;
      leaf name {
        type string;
      }
      action reset {
        ...
      }
    }
  }

  rpc powerdown {
    ...
  }
}
```

The reset action is tied to a single server `POST http://localhost:8080/restconf/data/server-farm:servers/server=server0/reset`, whereas shutting down the server farm itself is an RPC operation that acts on the module level `POST http://localhost:8080/restconf/operation/server-farm:powerdown`.

**Comment by dhubler** [comment]
I started looking at  implementation and here's a start

https://github.com/freeconf/gconf/commit/208c267e324887aa70b9bdafab43cec42791f952

With regard to implementation in gconf, what's left is:
1.) restrict new endpoint /operations/ to only top-level rpcs
2.) restrict /data/ no longer calling rpcs (which it can do today)
3.) implement [GET] /operations/ to deliver list of rpc names, but it's
unclear what format is.

disclaimer : You'll probably find a number of spec violations in gconf
because to-my-knowledge, it hasn't been used to interop with other
systems.  Some spec violations are known, many (like this one) are not.

**Comment by cgmcintyr** [comment]
Point 3 only seems to be referenced as a "might" in the specification, so could be separated into a nice-to-have ticket.

**Comment by dhubler** [comment]
re: Point 3 as optional
Oh, good, because it seems useless to me ;) .   Clients should parse the
full YANG and have all the info.

**Comment by pdumais** [comment]
This seems to be related to what I've opened yesterday: https://github.com/freeconf/restconf/issues/4
The inputs of RPC calls should be formatted differently too: https://github.com/freeconf/restconf/issues/5

**Comment by dhubler** [comment]
not going to sugar coat it, you'll probably find a large set of compliance
issues. I'm very motivated to get there, but I would need guidance and then
I suspect a concerted plan.

**Comment by HRogge** [comment]
Maybe this could be adapted to add more testcases for freeconf... two years ago I started helping a different restconf project. For this I assembled a list of Restconf testcases derived from the IETF RFCs in machine readable form.

https://github.com/fkie/ietf-restconf-testcases

**Comment by dhubler** [comment]
This issue has been resolved in the "compliance" branch which will soon merge into master
